feed/urls.py
from django.conf.urls import patterns, url

from feed.views import home

urlpatterns = patterns(
    '',
    url(r'^$', home, name="home")
)

webapp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^feed/', include('feed.urls', namespace="feed")),
    url(r'^login/$', login, {'template_name': 'project_1/login.html'}),
    url(r'^logout/$', logout, {'template_name': 'project_1/logout.html'}),
    url(r'^admin/', include(admin.site.urls)),
)

feed/models.py
"""
Simple Activity Feed Models.
"""
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class RegisteredUser(models.Model):
    """
    Registered user.

    I've changed a bit the provided model to change the flow of the relationship
    with other registered users. Instead of saying: "Who's tracking me?" I felt
    more comfortable by dealing with: "Who am I tracking?". This change
    improves the form in the admin page so when you add a registered user, you
    add the people he/she is going to track.
    """
    user = models.OneToOneField(User)
    tracking = models.ManyToManyField('self', verbose_name=_("Tracks"),
                                      related_name='tracks', blank=True,
                                      symmetrical=False)

    def __str__(self):
        return str(self.user)


class Ownable(models.Model):
    """
    Ownable.
    Abstract class representing an authored model.
    """
    user = models.ForeignKey(User, verbose_name=_("Author"),
                             related_name="%(class)ss")

    class Meta:
        abstract = True


class FeedItem(Ownable):
    """
    FeedItem.
    Published content of an User.
    """
    content = models.CharField("Content", max_length=1000)

    def __str__(self):
        return str(self.content)

feed/views.py
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import login_required

from feed.models import FeedItem

@login_required
def home(request):
    """
    User's home.
    """
    context = {
        "feed_list": None,
        "feed_title": "",
    }

    pfilter = request.GET.get("filter")
    if pfilter == "tracking":
        # Posts of everyone I'm tracking plus my own posts.
        context["feed_list"] = (FeedItem.objects.filter(user_id=request.user.id) | FeedItem.objects.filter(user__registereduser__tracks__user=request.user.id)).distinct()
        context["feed_title"] = _("Me and I'm tracking posts")
    elif pfilter == "all":
        # Everyone's posts (including my posts)
        context["feed_list"] = FeedItem.objects.all()
        context["feed_title"] = _("Everyone's posts")
    else:
        # (default) My posts
        context["feed_list"] = FeedItem.objects.filter(user_id=request.user.id)
        context["feed_title"] = _("My posts")

    return render(request, "feed/home.html", context)

feed/templates/feed/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>HOME</title>
</head>
<body>
    <h1>HOME {{ user }} ({{ user.id }})</h1>

    <ul>
        <li><a href="{% url 'feed:home' %}">My posts</a></li>
        <li><a href="{% url 'feed:home' %}?filter=tracking">Me and the posts of everyone I’m tracking</a></li>
        <li><a href="{% url 'feed:home' %}?filter=all">Everybody’s posts</a></li>
    </ul>

{% if feed_title %}
    <h3>{{ feed_title }}</h3>
    <ul>
    {% if feed_list %}
        {% for feed in feed_list %}
        <li>{{ feed }}</li>
        {% endfor %}
    {% else %}
        <li>No posts...</li>
    {% endif %}
    </ul>
{% endif %}

    <a href="{% url 'django.contrib.auth.views.logout' %}">Logout</a>
</body>
</html>

webapp/templates/project_1/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
</head>
<body>
    <!-- Header -->
    <h1>Login</h1>
    {% if form.errors %}
    <p style="color:red; font-weight: bold;">Your username and password didn't match. Please try again.</p>
    {% endif %}
    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
</body>
</html>

webapp/templates/project_1/logout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Logout</title>
</head>
<body>
    <h1>Logout successful!</h1>
    <a href="{% url 'django.contrib.auth.views.login' %}">Login</a>
</body>
</html>